// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoCommand.proto

package com.zml.command;

public final class DemoCommand {
  private DemoCommand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginRequestCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.LoginRequestCommand)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code message.LoginRequestCommand}
   */
  public  static final class LoginRequestCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.LoginRequestCommand)
      LoginRequestCommandOrBuilder {
    // Use LoginRequestCommand.newBuilder() to construct.
    private LoginRequestCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRequestCommand() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginRequestCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zml.command.DemoCommand.internal_static_message_LoginRequestCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zml.command.DemoCommand.internal_static_message_LoginRequestCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zml.command.DemoCommand.LoginRequestCommand.class, com.zml.command.DemoCommand.LoginRequestCommand.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zml.command.DemoCommand.LoginRequestCommand)) {
        return super.equals(obj);
      }
      com.zml.command.DemoCommand.LoginRequestCommand other = (com.zml.command.DemoCommand.LoginRequestCommand) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zml.command.DemoCommand.LoginRequestCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zml.command.DemoCommand.LoginRequestCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.LoginRequestCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zml.command.DemoCommand.LoginRequestCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.LoginRequestCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zml.command.DemoCommand.LoginRequestCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.LoginRequestCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zml.command.DemoCommand.LoginRequestCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.LoginRequestCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zml.command.DemoCommand.LoginRequestCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.LoginRequestCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zml.command.DemoCommand.LoginRequestCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zml.command.DemoCommand.LoginRequestCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.LoginRequestCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.LoginRequestCommand)
        com.zml.command.DemoCommand.LoginRequestCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zml.command.DemoCommand.internal_static_message_LoginRequestCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zml.command.DemoCommand.internal_static_message_LoginRequestCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zml.command.DemoCommand.LoginRequestCommand.class, com.zml.command.DemoCommand.LoginRequestCommand.Builder.class);
      }

      // Construct using com.zml.command.DemoCommand.LoginRequestCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zml.command.DemoCommand.internal_static_message_LoginRequestCommand_descriptor;
      }

      public com.zml.command.DemoCommand.LoginRequestCommand getDefaultInstanceForType() {
        return com.zml.command.DemoCommand.LoginRequestCommand.getDefaultInstance();
      }

      public com.zml.command.DemoCommand.LoginRequestCommand build() {
        com.zml.command.DemoCommand.LoginRequestCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zml.command.DemoCommand.LoginRequestCommand buildPartial() {
        com.zml.command.DemoCommand.LoginRequestCommand result = new com.zml.command.DemoCommand.LoginRequestCommand(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zml.command.DemoCommand.LoginRequestCommand) {
          return mergeFrom((com.zml.command.DemoCommand.LoginRequestCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zml.command.DemoCommand.LoginRequestCommand other) {
        if (other == com.zml.command.DemoCommand.LoginRequestCommand.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zml.command.DemoCommand.LoginRequestCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zml.command.DemoCommand.LoginRequestCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.LoginRequestCommand)
    }

    // @@protoc_insertion_point(class_scope:message.LoginRequestCommand)
    private static final com.zml.command.DemoCommand.LoginRequestCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zml.command.DemoCommand.LoginRequestCommand();
    }

    public static com.zml.command.DemoCommand.LoginRequestCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LoginRequestCommand>
        PARSER = new com.google.protobuf.AbstractParser<LoginRequestCommand>() {
      public LoginRequestCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginRequestCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginRequestCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequestCommand> getParserForType() {
      return PARSER;
    }

    public com.zml.command.DemoCommand.LoginRequestCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginResponseCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.LoginResponseCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string UserInfoCommand = 1;</code>
     */
    boolean hasUserInfoCommand();
    /**
     * <code>optional string UserInfoCommand = 1;</code>
     */
    java.lang.String getUserInfoCommand();
    /**
     * <code>optional string UserInfoCommand = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserInfoCommandBytes();
  }
  /**
   * Protobuf type {@code message.LoginResponseCommand}
   */
  public  static final class LoginResponseCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.LoginResponseCommand)
      LoginResponseCommandOrBuilder {
    // Use LoginResponseCommand.newBuilder() to construct.
    private LoginResponseCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginResponseCommand() {
      userInfoCommand_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginResponseCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              userInfoCommand_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zml.command.DemoCommand.internal_static_message_LoginResponseCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zml.command.DemoCommand.internal_static_message_LoginResponseCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zml.command.DemoCommand.LoginResponseCommand.class, com.zml.command.DemoCommand.LoginResponseCommand.Builder.class);
    }

    private int bitField0_;
    public static final int USERINFOCOMMAND_FIELD_NUMBER = 1;
    private volatile java.lang.Object userInfoCommand_;
    /**
     * <code>optional string UserInfoCommand = 1;</code>
     */
    public boolean hasUserInfoCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string UserInfoCommand = 1;</code>
     */
    public java.lang.String getUserInfoCommand() {
      java.lang.Object ref = userInfoCommand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userInfoCommand_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string UserInfoCommand = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserInfoCommandBytes() {
      java.lang.Object ref = userInfoCommand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userInfoCommand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userInfoCommand_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userInfoCommand_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zml.command.DemoCommand.LoginResponseCommand)) {
        return super.equals(obj);
      }
      com.zml.command.DemoCommand.LoginResponseCommand other = (com.zml.command.DemoCommand.LoginResponseCommand) obj;

      boolean result = true;
      result = result && (hasUserInfoCommand() == other.hasUserInfoCommand());
      if (hasUserInfoCommand()) {
        result = result && getUserInfoCommand()
            .equals(other.getUserInfoCommand());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserInfoCommand()) {
        hash = (37 * hash) + USERINFOCOMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getUserInfoCommand().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zml.command.DemoCommand.LoginResponseCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zml.command.DemoCommand.LoginResponseCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.LoginResponseCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zml.command.DemoCommand.LoginResponseCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.LoginResponseCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zml.command.DemoCommand.LoginResponseCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.LoginResponseCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zml.command.DemoCommand.LoginResponseCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.LoginResponseCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zml.command.DemoCommand.LoginResponseCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.LoginResponseCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zml.command.DemoCommand.LoginResponseCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zml.command.DemoCommand.LoginResponseCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.LoginResponseCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.LoginResponseCommand)
        com.zml.command.DemoCommand.LoginResponseCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zml.command.DemoCommand.internal_static_message_LoginResponseCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zml.command.DemoCommand.internal_static_message_LoginResponseCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zml.command.DemoCommand.LoginResponseCommand.class, com.zml.command.DemoCommand.LoginResponseCommand.Builder.class);
      }

      // Construct using com.zml.command.DemoCommand.LoginResponseCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userInfoCommand_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zml.command.DemoCommand.internal_static_message_LoginResponseCommand_descriptor;
      }

      public com.zml.command.DemoCommand.LoginResponseCommand getDefaultInstanceForType() {
        return com.zml.command.DemoCommand.LoginResponseCommand.getDefaultInstance();
      }

      public com.zml.command.DemoCommand.LoginResponseCommand build() {
        com.zml.command.DemoCommand.LoginResponseCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zml.command.DemoCommand.LoginResponseCommand buildPartial() {
        com.zml.command.DemoCommand.LoginResponseCommand result = new com.zml.command.DemoCommand.LoginResponseCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userInfoCommand_ = userInfoCommand_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zml.command.DemoCommand.LoginResponseCommand) {
          return mergeFrom((com.zml.command.DemoCommand.LoginResponseCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zml.command.DemoCommand.LoginResponseCommand other) {
        if (other == com.zml.command.DemoCommand.LoginResponseCommand.getDefaultInstance()) return this;
        if (other.hasUserInfoCommand()) {
          bitField0_ |= 0x00000001;
          userInfoCommand_ = other.userInfoCommand_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zml.command.DemoCommand.LoginResponseCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zml.command.DemoCommand.LoginResponseCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userInfoCommand_ = "";
      /**
       * <code>optional string UserInfoCommand = 1;</code>
       */
      public boolean hasUserInfoCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string UserInfoCommand = 1;</code>
       */
      public java.lang.String getUserInfoCommand() {
        java.lang.Object ref = userInfoCommand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userInfoCommand_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string UserInfoCommand = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserInfoCommandBytes() {
        java.lang.Object ref = userInfoCommand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userInfoCommand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string UserInfoCommand = 1;</code>
       */
      public Builder setUserInfoCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userInfoCommand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string UserInfoCommand = 1;</code>
       */
      public Builder clearUserInfoCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userInfoCommand_ = getDefaultInstance().getUserInfoCommand();
        onChanged();
        return this;
      }
      /**
       * <code>optional string UserInfoCommand = 1;</code>
       */
      public Builder setUserInfoCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userInfoCommand_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.LoginResponseCommand)
    }

    // @@protoc_insertion_point(class_scope:message.LoginResponseCommand)
    private static final com.zml.command.DemoCommand.LoginResponseCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zml.command.DemoCommand.LoginResponseCommand();
    }

    public static com.zml.command.DemoCommand.LoginResponseCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LoginResponseCommand>
        PARSER = new com.google.protobuf.AbstractParser<LoginResponseCommand>() {
      public LoginResponseCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginResponseCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginResponseCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResponseCommand> getParserForType() {
      return PARSER;
    }

    public com.zml.command.DemoCommand.LoginResponseCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserInfoCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.UserInfoCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string username = 2;</code>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 2;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional string position_x = 5;</code>
     */
    boolean hasPositionX();
    /**
     * <code>optional string position_x = 5;</code>
     */
    java.lang.String getPositionX();
    /**
     * <code>optional string position_x = 5;</code>
     */
    com.google.protobuf.ByteString
        getPositionXBytes();

    /**
     * <code>optional string position_z = 7;</code>
     */
    boolean hasPositionZ();
    /**
     * <code>optional string position_z = 7;</code>
     */
    java.lang.String getPositionZ();
    /**
     * <code>optional string position_z = 7;</code>
     */
    com.google.protobuf.ByteString
        getPositionZBytes();
  }
  /**
   * Protobuf type {@code message.UserInfoCommand}
   */
  public  static final class UserInfoCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.UserInfoCommand)
      UserInfoCommandOrBuilder {
    // Use UserInfoCommand.newBuilder() to construct.
    private UserInfoCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfoCommand() {
      id_ = "";
      username_ = "";
      positionX_ = "";
      positionZ_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfoCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              username_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              positionX_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              positionZ_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zml.command.DemoCommand.internal_static_message_UserInfoCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zml.command.DemoCommand.internal_static_message_UserInfoCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zml.command.DemoCommand.UserInfoCommand.class, com.zml.command.DemoCommand.UserInfoCommand.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object username_;
    /**
     * <code>optional string username = 2;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITION_X_FIELD_NUMBER = 5;
    private volatile java.lang.Object positionX_;
    /**
     * <code>optional string position_x = 5;</code>
     */
    public boolean hasPositionX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string position_x = 5;</code>
     */
    public java.lang.String getPositionX() {
      java.lang.Object ref = positionX_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          positionX_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string position_x = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPositionXBytes() {
      java.lang.Object ref = positionX_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        positionX_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITION_Z_FIELD_NUMBER = 7;
    private volatile java.lang.Object positionZ_;
    /**
     * <code>optional string position_z = 7;</code>
     */
    public boolean hasPositionZ() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string position_z = 7;</code>
     */
    public java.lang.String getPositionZ() {
      java.lang.Object ref = positionZ_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          positionZ_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string position_z = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPositionZBytes() {
      java.lang.Object ref = positionZ_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        positionZ_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, positionX_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, positionZ_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, positionX_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, positionZ_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zml.command.DemoCommand.UserInfoCommand)) {
        return super.equals(obj);
      }
      com.zml.command.DemoCommand.UserInfoCommand other = (com.zml.command.DemoCommand.UserInfoCommand) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasUsername() == other.hasUsername());
      if (hasUsername()) {
        result = result && getUsername()
            .equals(other.getUsername());
      }
      result = result && (hasPositionX() == other.hasPositionX());
      if (hasPositionX()) {
        result = result && getPositionX()
            .equals(other.getPositionX());
      }
      result = result && (hasPositionZ() == other.hasPositionZ());
      if (hasPositionZ()) {
        result = result && getPositionZ()
            .equals(other.getPositionZ());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasUsername()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUsername().hashCode();
      }
      if (hasPositionX()) {
        hash = (37 * hash) + POSITION_X_FIELD_NUMBER;
        hash = (53 * hash) + getPositionX().hashCode();
      }
      if (hasPositionZ()) {
        hash = (37 * hash) + POSITION_Z_FIELD_NUMBER;
        hash = (53 * hash) + getPositionZ().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zml.command.DemoCommand.UserInfoCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zml.command.DemoCommand.UserInfoCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.UserInfoCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zml.command.DemoCommand.UserInfoCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.UserInfoCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zml.command.DemoCommand.UserInfoCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.UserInfoCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zml.command.DemoCommand.UserInfoCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.UserInfoCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zml.command.DemoCommand.UserInfoCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.UserInfoCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zml.command.DemoCommand.UserInfoCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zml.command.DemoCommand.UserInfoCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.UserInfoCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.UserInfoCommand)
        com.zml.command.DemoCommand.UserInfoCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zml.command.DemoCommand.internal_static_message_UserInfoCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zml.command.DemoCommand.internal_static_message_UserInfoCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zml.command.DemoCommand.UserInfoCommand.class, com.zml.command.DemoCommand.UserInfoCommand.Builder.class);
      }

      // Construct using com.zml.command.DemoCommand.UserInfoCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        positionX_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        positionZ_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zml.command.DemoCommand.internal_static_message_UserInfoCommand_descriptor;
      }

      public com.zml.command.DemoCommand.UserInfoCommand getDefaultInstanceForType() {
        return com.zml.command.DemoCommand.UserInfoCommand.getDefaultInstance();
      }

      public com.zml.command.DemoCommand.UserInfoCommand build() {
        com.zml.command.DemoCommand.UserInfoCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zml.command.DemoCommand.UserInfoCommand buildPartial() {
        com.zml.command.DemoCommand.UserInfoCommand result = new com.zml.command.DemoCommand.UserInfoCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.positionX_ = positionX_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.positionZ_ = positionZ_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zml.command.DemoCommand.UserInfoCommand) {
          return mergeFrom((com.zml.command.DemoCommand.UserInfoCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zml.command.DemoCommand.UserInfoCommand other) {
        if (other == com.zml.command.DemoCommand.UserInfoCommand.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000002;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPositionX()) {
          bitField0_ |= 0x00000004;
          positionX_ = other.positionX_;
          onChanged();
        }
        if (other.hasPositionZ()) {
          bitField0_ |= 0x00000008;
          positionZ_ = other.positionZ_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zml.command.DemoCommand.UserInfoCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zml.command.DemoCommand.UserInfoCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 2;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object positionX_ = "";
      /**
       * <code>optional string position_x = 5;</code>
       */
      public boolean hasPositionX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string position_x = 5;</code>
       */
      public java.lang.String getPositionX() {
        java.lang.Object ref = positionX_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            positionX_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string position_x = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPositionXBytes() {
        java.lang.Object ref = positionX_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          positionX_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string position_x = 5;</code>
       */
      public Builder setPositionX(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        positionX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string position_x = 5;</code>
       */
      public Builder clearPositionX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        positionX_ = getDefaultInstance().getPositionX();
        onChanged();
        return this;
      }
      /**
       * <code>optional string position_x = 5;</code>
       */
      public Builder setPositionXBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        positionX_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object positionZ_ = "";
      /**
       * <code>optional string position_z = 7;</code>
       */
      public boolean hasPositionZ() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string position_z = 7;</code>
       */
      public java.lang.String getPositionZ() {
        java.lang.Object ref = positionZ_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            positionZ_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string position_z = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPositionZBytes() {
        java.lang.Object ref = positionZ_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          positionZ_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string position_z = 7;</code>
       */
      public Builder setPositionZ(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        positionZ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string position_z = 7;</code>
       */
      public Builder clearPositionZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        positionZ_ = getDefaultInstance().getPositionZ();
        onChanged();
        return this;
      }
      /**
       * <code>optional string position_z = 7;</code>
       */
      public Builder setPositionZBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        positionZ_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.UserInfoCommand)
    }

    // @@protoc_insertion_point(class_scope:message.UserInfoCommand)
    private static final com.zml.command.DemoCommand.UserInfoCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zml.command.DemoCommand.UserInfoCommand();
    }

    public static com.zml.command.DemoCommand.UserInfoCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UserInfoCommand>
        PARSER = new com.google.protobuf.AbstractParser<UserInfoCommand>() {
      public UserInfoCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserInfoCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfoCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfoCommand> getParserForType() {
      return PARSER;
    }

    public com.zml.command.DemoCommand.UserInfoCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserInfoListCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.UserInfoListCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string UserInfoCommand = 1;</code>
     */
    java.util.List<java.lang.String>
        getUserInfoCommandList();
    /**
     * <code>repeated string UserInfoCommand = 1;</code>
     */
    int getUserInfoCommandCount();
    /**
     * <code>repeated string UserInfoCommand = 1;</code>
     */
    java.lang.String getUserInfoCommand(int index);
    /**
     * <code>repeated string UserInfoCommand = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserInfoCommandBytes(int index);
  }
  /**
   * Protobuf type {@code message.UserInfoListCommand}
   */
  public  static final class UserInfoListCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.UserInfoListCommand)
      UserInfoListCommandOrBuilder {
    // Use UserInfoListCommand.newBuilder() to construct.
    private UserInfoListCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfoListCommand() {
      userInfoCommand_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfoListCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                userInfoCommand_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              userInfoCommand_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          userInfoCommand_ = userInfoCommand_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zml.command.DemoCommand.internal_static_message_UserInfoListCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zml.command.DemoCommand.internal_static_message_UserInfoListCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zml.command.DemoCommand.UserInfoListCommand.class, com.zml.command.DemoCommand.UserInfoListCommand.Builder.class);
    }

    public static final int USERINFOCOMMAND_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList userInfoCommand_;
    /**
     * <code>repeated string UserInfoCommand = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getUserInfoCommandList() {
      return userInfoCommand_;
    }
    /**
     * <code>repeated string UserInfoCommand = 1;</code>
     */
    public int getUserInfoCommandCount() {
      return userInfoCommand_.size();
    }
    /**
     * <code>repeated string UserInfoCommand = 1;</code>
     */
    public java.lang.String getUserInfoCommand(int index) {
      return userInfoCommand_.get(index);
    }
    /**
     * <code>repeated string UserInfoCommand = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserInfoCommandBytes(int index) {
      return userInfoCommand_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < userInfoCommand_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userInfoCommand_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < userInfoCommand_.size(); i++) {
          dataSize += computeStringSizeNoTag(userInfoCommand_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getUserInfoCommandList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zml.command.DemoCommand.UserInfoListCommand)) {
        return super.equals(obj);
      }
      com.zml.command.DemoCommand.UserInfoListCommand other = (com.zml.command.DemoCommand.UserInfoListCommand) obj;

      boolean result = true;
      result = result && getUserInfoCommandList()
          .equals(other.getUserInfoCommandList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUserInfoCommandCount() > 0) {
        hash = (37 * hash) + USERINFOCOMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getUserInfoCommandList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zml.command.DemoCommand.UserInfoListCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zml.command.DemoCommand.UserInfoListCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.UserInfoListCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zml.command.DemoCommand.UserInfoListCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.UserInfoListCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zml.command.DemoCommand.UserInfoListCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.UserInfoListCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zml.command.DemoCommand.UserInfoListCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.UserInfoListCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zml.command.DemoCommand.UserInfoListCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zml.command.DemoCommand.UserInfoListCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zml.command.DemoCommand.UserInfoListCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zml.command.DemoCommand.UserInfoListCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.UserInfoListCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.UserInfoListCommand)
        com.zml.command.DemoCommand.UserInfoListCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zml.command.DemoCommand.internal_static_message_UserInfoListCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zml.command.DemoCommand.internal_static_message_UserInfoListCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zml.command.DemoCommand.UserInfoListCommand.class, com.zml.command.DemoCommand.UserInfoListCommand.Builder.class);
      }

      // Construct using com.zml.command.DemoCommand.UserInfoListCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userInfoCommand_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zml.command.DemoCommand.internal_static_message_UserInfoListCommand_descriptor;
      }

      public com.zml.command.DemoCommand.UserInfoListCommand getDefaultInstanceForType() {
        return com.zml.command.DemoCommand.UserInfoListCommand.getDefaultInstance();
      }

      public com.zml.command.DemoCommand.UserInfoListCommand build() {
        com.zml.command.DemoCommand.UserInfoListCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zml.command.DemoCommand.UserInfoListCommand buildPartial() {
        com.zml.command.DemoCommand.UserInfoListCommand result = new com.zml.command.DemoCommand.UserInfoListCommand(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          userInfoCommand_ = userInfoCommand_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userInfoCommand_ = userInfoCommand_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zml.command.DemoCommand.UserInfoListCommand) {
          return mergeFrom((com.zml.command.DemoCommand.UserInfoListCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zml.command.DemoCommand.UserInfoListCommand other) {
        if (other == com.zml.command.DemoCommand.UserInfoListCommand.getDefaultInstance()) return this;
        if (!other.userInfoCommand_.isEmpty()) {
          if (userInfoCommand_.isEmpty()) {
            userInfoCommand_ = other.userInfoCommand_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserInfoCommandIsMutable();
            userInfoCommand_.addAll(other.userInfoCommand_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zml.command.DemoCommand.UserInfoListCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zml.command.DemoCommand.UserInfoListCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList userInfoCommand_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUserInfoCommandIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          userInfoCommand_ = new com.google.protobuf.LazyStringArrayList(userInfoCommand_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string UserInfoCommand = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getUserInfoCommandList() {
        return userInfoCommand_.getUnmodifiableView();
      }
      /**
       * <code>repeated string UserInfoCommand = 1;</code>
       */
      public int getUserInfoCommandCount() {
        return userInfoCommand_.size();
      }
      /**
       * <code>repeated string UserInfoCommand = 1;</code>
       */
      public java.lang.String getUserInfoCommand(int index) {
        return userInfoCommand_.get(index);
      }
      /**
       * <code>repeated string UserInfoCommand = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserInfoCommandBytes(int index) {
        return userInfoCommand_.getByteString(index);
      }
      /**
       * <code>repeated string UserInfoCommand = 1;</code>
       */
      public Builder setUserInfoCommand(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserInfoCommandIsMutable();
        userInfoCommand_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string UserInfoCommand = 1;</code>
       */
      public Builder addUserInfoCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserInfoCommandIsMutable();
        userInfoCommand_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string UserInfoCommand = 1;</code>
       */
      public Builder addAllUserInfoCommand(
          java.lang.Iterable<java.lang.String> values) {
        ensureUserInfoCommandIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userInfoCommand_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string UserInfoCommand = 1;</code>
       */
      public Builder clearUserInfoCommand() {
        userInfoCommand_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string UserInfoCommand = 1;</code>
       */
      public Builder addUserInfoCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserInfoCommandIsMutable();
        userInfoCommand_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.UserInfoListCommand)
    }

    // @@protoc_insertion_point(class_scope:message.UserInfoListCommand)
    private static final com.zml.command.DemoCommand.UserInfoListCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zml.command.DemoCommand.UserInfoListCommand();
    }

    public static com.zml.command.DemoCommand.UserInfoListCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UserInfoListCommand>
        PARSER = new com.google.protobuf.AbstractParser<UserInfoListCommand>() {
      public UserInfoListCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserInfoListCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfoListCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfoListCommand> getParserForType() {
      return PARSER;
    }

    public com.zml.command.DemoCommand.UserInfoListCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_LoginRequestCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_LoginRequestCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_LoginResponseCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_LoginResponseCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_UserInfoCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_UserInfoCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_UserInfoListCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_UserInfoListCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021DemoCommand.proto\022\007message\"\025\n\023LoginReq" +
      "uestCommand\"/\n\024LoginResponseCommand\022\027\n\017U" +
      "serInfoCommand\030\001 \001(\t\"W\n\017UserInfoCommand\022" +
      "\n\n\002id\030\001 \001(\t\022\020\n\010username\030\002 \001(\t\022\022\n\npositio" +
      "n_x\030\005 \001(\t\022\022\n\nposition_z\030\007 \001(\t\".\n\023UserInf" +
      "oListCommand\022\027\n\017UserInfoCommand\030\001 \003(\tB\036\n" +
      "\017com.zml.commandB\013DemoCommand"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_LoginRequestCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_LoginRequestCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_LoginRequestCommand_descriptor,
        new java.lang.String[] { });
    internal_static_message_LoginResponseCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_LoginResponseCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_LoginResponseCommand_descriptor,
        new java.lang.String[] { "UserInfoCommand", });
    internal_static_message_UserInfoCommand_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_UserInfoCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_UserInfoCommand_descriptor,
        new java.lang.String[] { "Id", "Username", "PositionX", "PositionZ", });
    internal_static_message_UserInfoListCommand_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_message_UserInfoListCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_UserInfoListCommand_descriptor,
        new java.lang.String[] { "UserInfoCommand", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
